In [3]:
import numpy as np

#**Step - 2) Create arrays**

- 1D array

In [5]:
One_D_Array = np.array([1,2,3,4,5])
print(One_D_Array)

[1 2 3 4 5]


- 2D array

In [7]:
Two_D_Array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(Two_D_Array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


- 3D array

In [10]:
Three_D_Array = np.array([[[1,2,3], [4,5,6]],
[[7,8,9], [10,11,12]]])
print(Three_D_Array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#**Step - 3) Check shape and size**

In [16]:
print('Shape:', One_D_Array.shape)

Shape: (5,)


*Means One_D_Array contains 5 elements, often displayed as 5 columns*

In [18]:
print('Shape:', Two_D_Array.shape)

Shape: (2, 5)


*The array has two row and 5 columns*

In [20]:
print('Shape:', Three_D_Array.shape)

Shape: (2, 2, 3)


*The array has 2 depth means 2 separate 2D arrays and 
2 rows in each 2D array and
3 columns in each 2D array*

In [22]:
print('Size:', One_D_Array.size)

Size: 5


*Means the One D array contains 5 elements*

In [24]:
print('Size:', Two_D_Array.size)

Size: 10


In [26]:
print('Size:', Three_D_Array.size)

Size: 12


#**Useful Array Functions**

In [86]:
print('Empty_Values:\n', np.empty((3,3)))

Empty_Values:
 [[11.50113971 28.8600554  23.84240135]
 [16.56964494 15.12061634 16.83362353]
 [14.17899715 22.39429754 22.39540391]]


In [32]:
print('Zeros:', np.zeros((2,3)))

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
print('Ones:', np.ones((3,3)))

Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
print('Ones:', np.ones((2,2,3)))

Ones: [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#**- Values between 0 and 1 but not including 1(decimal/floating numbers)**

In [38]:
print('Random:', np.random.rand(2,2))

Random: [[0.50188189 0.13805576]
 [0.33367405 0.22133505]]


*- But if you want random integers or other ranges - np.random.randint(start, stop, size) with this you'll get random integers not in ordred*

In [56]:
print('Random_int:\n', np.random.randint(2,15, size = (2,3)))

Random_int:
 [[ 6  4  7]
 [ 6  4 12]]


*Use np.random.uniform(low, high, size) for custom float range*

In [58]:
np.random.uniform(10,30, size = (3,3))

array([[11.50113971, 28.8600554 , 23.84240135],
       [16.56964494, 15.12061634, 16.83362353],
       [14.17899715, 22.39429754, 22.39540391]])

#**Transpose Function**

*The Transpose() Function in Numpy is used to flip the dimensions of an array - commonly used for 2D arrays(matrices) or multidimensional arrays*

In [42]:
Transposed_Two_D_Array = (Two_D_Array.transpose())
print(Transposed_Two_D_Array)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [50]:
print('Original 2D array:\n', Two_D_Array)

Original 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


*The example clearly shows that with the help of the transpose function, we can flip the dimensions of an array. For instance, if the original data has 2 rows and 5 columns, using the transpose function will change it to 5 rows and 2 columns.*

#**np.arange() in NumPy is used to create arrays with regularly spaced values. Here is its syntax: np.arange(start, end, step)**

In [88]:
arange = np.arange(1,10)
print(arange)

[1 2 3 4 5 6 7 8 9]


In [92]:
arange_with_step = np.arange(1,20,2)
print(arange_with_step)

[ 1  3  5  7  9 11 13 15 17 19]


#**Array Operation**

In [114]:
x = np.array([10,20,30])
y = np.array([5,6,7])
print('Add:', x + y)

Add: [15 26 37]


In [116]:
print('Multiply:', x*y)

Multiply: [ 50 120 210]


In [118]:
print('Subtract:', x-y)

Subtract: [ 5 14 23]


In [130]:
print(('Square root:', np.sqrt(x)))

('Square root:', array([3.16227766, 4.47213595, 5.47722558]))


In [136]:
print('divide:\n', x / y)

divide:
 [2.         3.33333333 4.28571429]


#**Indexing and Slicing**

In [8]:
a = np.arange(1,51)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [10]:
b = a.reshape(10,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [12]:
b[0]

array([1, 2, 3, 4, 5])

In [14]:
b[2]

array([11, 12, 13, 14, 15])

In [16]:
b[0,0]

1

In [18]:
b[3,4]

20

In [20]:
b[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
b[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [24]:
b[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [28]:
b[2:5,4]

array([15, 20, 25])

In [30]:
b[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

#**Reshaping Arrays in Numpy**

*Reshaping means changing the shape of the array (like from 1D to 2D, or 2D to 3D), without changing the data.*

In [32]:
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
print(x.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
print(x.reshape(2,2,3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


#**Aggregate Functions in numpy**

In [48]:
arr = np.array([[10,20], [30,40]])
print(arr)

[[10 20]
 [30 40]]


In [50]:
print('Sum', arr.sum())

Sum 100


In [52]:
print('Min', arr.min())

Min 10


In [56]:
print('Max', arr.max())

Max 40


In [58]:
print('Mean', arr.mean())

Mean 25.0


In [60]:
print('SD', arr.std())

SD 11.180339887498949


*we can also apply functions row-wise and column-wise using axis*

In [62]:
print('Sum(rows):', arr.sum(axis = 1))

Sum(rows): [30 70]


In [64]:
print('Sum(columns):', arr.sum(axis = 0))

Sum(columns): [40 60]


#**np.eye()- Identity matrix**

In [68]:
Identity_matrix = np.eye(5)
print(Identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#**np.full()-Create array with a specific value**

In [70]:
filled_array = np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]
